---
apiVersion: v1
kind: Namespace
metadata:
  name:  iperf-server
---
apiVersion: v1
kind: Namespace
metadata:
  name:  iperf-client
---
apiVersion: v1
kind: Pod
metadata:
  name: iperf3-server
  labels:
    app: iperf3-server
  namespace: iperf
spec:
  containers:
    - name: iperf3-server
      image: networkstatic/iperf3
      args: ['-s']
      orts:
      - containerPort: 5201
        name: server
---
apiVersion: v1
kind: Service
metadata:
  name: iperf3-server
  namespace: iperf-server
spec:
  selector:
    app: iperf3-server
  ports:
  - protocol: TCP
    port: 5201
    targetPort: server  
---
apiVersion: v1
kind: Pod
metadata:
  name: iperf3-clients
  labels:
    app: iperf3-client
  namespace: iperf-client
spec:
  containers:
  - name: iperf3-client
    image: networkstatic/iperf3
    command: ['/bin/sh', '-c', 'sleep infinity']

