---
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/cluster-service: "true"
  name: default
spec:
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - '*'
  allowedUnsafeSysctls:
  - '*' 
  fsGroup:
    rule: RunAsAny
  hostIPC: true
  hostNetwork: true
  hostPID: true
  hostPorts:
  - max: 65535
    min: 0
  privileged: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: edu20
    app.kubernetes.io/part-of: edu20
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/cluster-service: "true"    
  name: default
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
  resourceNames:
  - default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: edu20
    app.kubernetes.io/part-of: edu20
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/cluster-service: "true"     
  name: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
- kind: Group
  name: system:serviceaccounts:default
  apiGroup: rbac.authorization.k8s.io
