apiVersion: config.istio.io/v1alpha2
kind: instance
metadata:
  name: newlog
  namespace: istio-system
spec:
  compiledTemplate: logentry
  params:
    severity: '"info"'
    timestamp: request.time
    variables:
      context_protocol: context.protocol | "none"
      source: source.labels["app"] | source.workload.name | "unknown"
      source_namespace: source.namespace | "unknown"
      source_pod: source.name | "unknown"
      source_version: source.labels["version"] | "unknown"
      source_workload: source.workload.name | "unknown"
      source_workload_uid: source.workload.uid | "unknown"
      user: source.principal | "unknown"
      destination: destination.labels["app"] | destination.workload.name | "unknown"
      destination_namespace: destination.namespace | "unknown"
      destination_pod: destination.name | "unknown"
      destination_version: destination.labels["version"] | "unknown"
      destination_svc_host: destination.service.host | "unknown"
      request_id: request.headers["x-request-id"] | ""
      request_host: request.host | "none"
      request_method: request.method | "none"
      request_useragent: request.useragent | "none"
      responseCode: response.code | 0
      responseSize: response.size | 0
      latency: response.duration | "0ms"
      connectionMtls: connection.mtls | false
      url: request.path | ""
    monitored_resource_type: '"UNSPECIFIED"'
---