apiVersion: v1
kind: Service
metadata:
  labels:
    app: istio-ingressgateway
    chart: gateways
    heritage: Tiller
    istio: ingress-gateway-ext
    release: istio
  name: ingress-gateway-ext
  namespace: istio-system
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: status-port
    nodePort: 32020
    port: 15020
    protocol: TCP
    targetPort: 15020
  - name: http2
    nodePort: 32080
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    nodePort: 32443
    port: 443
    protocol: TCP
    targetPort: 443
  - name: tcp
    nodePort: 31500
    port: 31400
    protocol: TCP
    targetPort: 31400
  - name: tls
    nodePort: 32543
    port: 15443
    protocol: TCP
    targetPort: 15443
  selector:
    app: istio-ingressgateway
    istio: ingress-gateway-ext
    release: istio
  sessionAffinity: None
  type: LoadBalancer