{
 "title": "Istio Mixer Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "adapter", "label": "Adapter", "query": "label_values(adapter)" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "<center><h2>Deployed Versions</h2></center>"
  },
  {
   "title": "Mixer Versions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(istio_build{component=\"mixer\"}) by (tag)",
     "legendFormat": "{{ tag }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 8 },
   "content": "<center><h2>Resource Usage</h2></center>"
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(process_virtual_memory_bytes{job=~\"istio-telemetry|istio-policy\"}) by (job)",
     "legendFormat": "Virtual Memory ({{ job }})"
    },
    {
     "expr": "sum(process_resident_memory_bytes{job=~\"istio-telemetry|istio-policy\"}) by (job)",
     "legendFormat": "Resident Memory ({{ job }})"
    },
    {
     "expr": "sum(go_memstats_alloc_bytes{job=~\"istio-telemetry|istio-policy\"}) by (job)",
     "legendFormat": "Alloc ({{ job }})"
    },
    {
     "expr": "sum(go_memstats_heap_inuse_bytes{job=~\"istio-telemetry|istio-policy\"}) by (job)",
     "legendFormat": "Heap in-use ({{ job }})"
    },
    {
     "expr": "sum(go_memstats_stack_inuse_bytes{job=~\"istio-telemetry|istio-policy\"}) by (job)",
     "legendFormat": "Stack in-use ({{ job }})"
    },
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{container_name=~\"mixer|istio-proxy\", pod_name=~\"istio-telemetry-.*|istio-policy-.*\"}, \"service\", \"$1\" , \"pod_name\", \"(istio-telemetry|istio-policy)-.*\")) by (service)",
     "legendFormat": "{{ service }} total (k8s)"
    },
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{container_name=~\"mixer|istio-proxy\", pod_name=~\"istio-telemetry-.*|istio-policy-.*\"}, \"service\", \"$1\" , \"pod_name\", \"(istio-telemetry|istio-policy)-.*\")) by (container_name, service)",
     "legendFormat": "{{ service }} - {{ container_name }} (k8s)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum(rate(container_cpu_usage_seconds_total{container_name=~\"mixer|istio-proxy\", pod_name=~\"istio-telemetry-.*|istio-policy-.*\"}[1m])) by (pod_name), \"service\", \"$1\" , \"pod_name\", \"(istio-telemetry|istio-policy)-.*\")",
     "legendFormat": "{{ service }} total (k8s)"
    },
    {
     "expr": "label_replace(sum(rate(container_cpu_usage_seconds_total{container_name=~\"mixer|istio-proxy\", pod_name=~\"istio-telemetry-.*|istio-policy-.*\"}[1m])) by (container_name, pod_name), \"service\", \"$1\" , \"pod_name\", \"(istio-telemetry|istio-policy)-.*\")",
     "legendFormat": "{{ service }} - {{ container_name }} (k8s)"
    },
    {
     "expr": "sum(irate(process_cpu_seconds_total{job=~\"istio-telemetry|istio-policy\"}[1m])) by (job)",
     "legendFormat": "{{ job }} (self-reported)"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(container_fs_usage_bytes{container_name=~\"mixer|istio-proxy\", pod_name=~\"istio-telemetry-.*|istio-policy-.*\"}, \"service\", \"$1\" , \"pod_name\", \"(istio-telemetry|istio-policy)-.*\")) by (container_name, service)",
     "legendFormat": "{{ service }} - {{ container_name }}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_goroutines{job=~\"istio-telemetry|istio-policy\"}) by (job)",
     "legendFormat": "Number of Goroutines ({{ job }})"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 18 },
   "content": "<center><h2>Mixer Overview</h2></center>"
  },
  {
   "title": "Incoming Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_io_server_completed_rpcs[1m]))",
     "legendFormat": "mixer (Total)"
    },
    {
     "expr": "sum(rate(grpc_io_server_completed_rpcs[1m])) by (grpc_server_method)",
     "legendFormat": "mixer ({{ grpc_server_method }})"
    }
   ]
  },
  {
   "title": "Response Durations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(grpc_io_server_server_latency_bucket{}[1m])) by (grpc_server_method, le))",
     "legendFormat": "{{ grpc_server_method }} 0.5"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(grpc_io_server_server_latency_bucket{}[1m])) by (grpc_server_method, le))",
     "legendFormat": "{{ grpc_server_method }} 0.9"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_io_server_server_latency_bucket{}[1m])) by (grpc_server_method, le))",
     "legendFormat": "{{ grpc_server_method }} 0.99"
    }
   ]
  },
  {
   "title": "Server Error Rate (5xx responses)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{grpc_code=~\"Unknown|Unimplemented|Internal|DataLoss\"}[1m])) by (grpc_method)",
     "legendFormat": "Mixer {{ grpc_method }}"
    }
   ]
  },
  {
   "title": "Non-successes (4xxs)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(grpc_server_handled_total{grpc_code!=\"OK\",grpc_service=~\".*Mixer\"}[1m])) by (grpc_method)",
     "legendFormat": "Mixer {{ grpc_method }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 27 },
   "content": "<center><h2>Adapters and Config</h2></center>"
  },
  {
   "title": "Adapter Dispatch Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(mixer_runtime_dispatches_total{adapter=~\"$adapter\"}[1m])) by (adapter)",
     "legendFormat": "{{ adapter }}"
    }
   ]
  },
  {
   "title": "Adapter Dispatch Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(mixer_runtime_dispatch_duration_seconds_bucket{adapter=~\"$adapter\"}[1m])) by (adapter, le))",
     "legendFormat": "{{ adapter }} - p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(irate(mixer_runtime_dispatch_duration_seconds_bucket{adapter=~\"$adapter\"}[1m])) by (adapter, le))",
     "legendFormat": "{{ adapter }} - p90 "
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(mixer_runtime_dispatch_duration_seconds_bucket{adapter=~\"$adapter\"}[1m])) by (adapter, le))",
     "legendFormat": "{{ adapter }} - p99"
    }
   ]
  },
  {
   "title": "Rules",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scalar(topk(1, max(mixer_config_rule_config_count) by (configID)))",
     "legendFormat": "Rules"
    },
    {
     "expr": "scalar(topk(1, max(mixer_config_rule_config_error_count) by (configID)))",
     "legendFormat": "Config Errors"
    },
    {
     "expr": "scalar(topk(1, max(mixer_config_rule_config_match_error_count) by (configID)))",
     "legendFormat": "Match Errors"
    },
    {
     "expr": "scalar(topk(1, max(mixer_config_unsatisfied_action_handler_count) by (configID)))",
     "legendFormat": "Unsatisfied Actions"
    }
   ]
  },
  {
   "title": "Instances in Latest Config",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scalar(topk(1, max(mixer_config_instance_config_count) by (configID)))",
     "legendFormat": "Instances"
    }
   ]
  },
  {
   "title": "Handlers in Latest Config",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scalar(topk(1, max(mixer_config_handler_config_count) by (configID)))",
     "legendFormat": "Handlers"
    }
   ]
  },
  {
   "title": "Attributes in Latest Config",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scalar(topk(1, max(mixer_config_attribute_count) by (configID)))",
     "legendFormat": "Attributes"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 44 },
   "content": "<center><h2>Individual Adapters</h2></center>"
  },
  { "title": "$adapter Adapter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 }, "repeat": "adapter" },
  {
   "title": "Dispatch Count By Handler",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(irate(mixer_runtime_dispatches_total{adapter=\"$adapter\"}[1m]),\"handler\", \"$1 ($3)\", \"handler\", \"(.*)\\\\.(.*)\\\\.(.*)\")",
     "legendFormat": "{{ handler }} (error: {{  error }})"
    }
   ]
  },
  {
   "title": "Dispatch Duration By Handler",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "label_replace(histogram_quantile(0.5, sum(rate(mixer_runtime_dispatch_duration_seconds_bucket{adapter=\"$adapter\"}[1m])) by (handler, error, le)),  \"handler_short\", \"$1 ($3)\", \"handler\", \"(.*)\\\\.(.*)\\\\.(.*)\")",
     "legendFormat": "p50 - {{ handler_short }} (error: {{ error }})"
    },
    {
     "expr": "label_replace(histogram_quantile(0.9, sum(irate(mixer_runtime_dispatch_duration_seconds_bucket{adapter=\"$adapter\"}[1m])) by (handler, error, le)),  \"handler_short\", \"$1 ($3)\", \"handler\", \"(.*)\\\\.(.*)\\\\.(.*)\")",
     "legendFormat": "p90 - {{ handler_short }} (error: {{ error }})"
    },
    {
     "expr": "label_replace(histogram_quantile(0.99, sum(irate(mixer_runtime_dispatch_duration_seconds_bucket{adapter=\"$adapter\"}[1m])) by (handler, error, le)),  \"handler_short\", \"$1 ($3)\", \"handler\", \"(.*)\\\\.(.*)\\\\.(.*)\")",
     "legendFormat": "p99 - {{ handler_short }} (error: {{ error }})"
    }
   ]
  },
  { "title": "$adapter Adapter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Dispatch Count By Handler",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(irate(mixer_runtime_dispatches_total{adapter=\"$adapter\"}[1m]),\"handler\", \"$1 ($3)\", \"handler\", \"(.*)\\\\.(.*)\\\\.(.*)\")",
     "legendFormat": "{{ handler }} (error: {{  error }})"
    }
   ]
  },
  {
   "title": "Dispatch Duration By Handler",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "label_replace(histogram_quantile(0.5, sum(rate(mixer_runtime_dispatch_duration_seconds_bucket{adapter=\"$adapter\"}[1m])) by (handler, error, le)),  \"handler_short\", \"$1 ($3)\", \"handler\", \"(.*)\\\\.(.*)\\\\.(.*)\")",
     "legendFormat": "p50 - {{ handler_short }} (error: {{ error }})"
    },
    {
     "expr": "label_replace(histogram_quantile(0.9, sum(irate(mixer_runtime_dispatch_duration_seconds_bucket{adapter=\"$adapter\"}[1m])) by (handler, error, le)),  \"handler_short\", \"$1 ($3)\", \"handler\", \"(.*)\\\\.(.*)\\\\.(.*)\")",
     "legendFormat": "p90 - {{ handler_short }} (error: {{ error }})"
    },
    {
     "expr": "label_replace(histogram_quantile(0.99, sum(irate(mixer_runtime_dispatch_duration_seconds_bucket{adapter=\"$adapter\"}[1m])) by (handler, error, le)),  \"handler_short\", \"$1 ($3)\", \"handler\", \"(.*)\\\\.(.*)\\\\.(.*)\")",
     "legendFormat": "p99 - {{ handler_short }} (error: {{ error }})"
    }
   ]
  },
  { "title": "$adapter Adapter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Dispatch Count By Handler",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(irate(mixer_runtime_dispatches_total{adapter=\"$adapter\"}[1m]),\"handler\", \"$1 ($3)\", \"handler\", \"(.*)\\\\.(.*)\\\\.(.*)\")",
     "legendFormat": "{{ handler }} (error: {{  error }})"
    }
   ]
  },
  {
   "title": "Dispatch Duration By Handler",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "label_replace(histogram_quantile(0.5, sum(rate(mixer_runtime_dispatch_duration_seconds_bucket{adapter=\"$adapter\"}[1m])) by (handler, error, le)),  \"handler_short\", \"$1 ($3)\", \"handler\", \"(.*)\\\\.(.*)\\\\.(.*)\")",
     "legendFormat": "p50 - {{ handler_short }} (error: {{ error }})"
    },
    {
     "expr": "label_replace(histogram_quantile(0.9, sum(irate(mixer_runtime_dispatch_duration_seconds_bucket{adapter=\"$adapter\"}[1m])) by (handler, error, le)),  \"handler_short\", \"$1 ($3)\", \"handler\", \"(.*)\\\\.(.*)\\\\.(.*)\")",
     "legendFormat": "p90 - {{ handler_short }} (error: {{ error }})"
    },
    {
     "expr": "label_replace(histogram_quantile(0.99, sum(irate(mixer_runtime_dispatch_duration_seconds_bucket{adapter=\"$adapter\"}[1m])) by (handler, error, le)),  \"handler_short\", \"$1 ($3)\", \"handler\", \"(.*)\\\\.(.*)\\\\.(.*)\")",
     "legendFormat": "p99 - {{ handler_short }} (error: {{ error }})"
    }
   ]
  }
 ]
}